version: "3"

volumes:
  db_maria:

services:

  mariadb:
    image: mariadb
    restart: on-failure
    ports:
      - "127.0.0.1:420:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abc
      MYSQL_DATABASE: schwurbelwatch
    volumes:
      - db_maria:/var/lib/mysql
    
  # mongodb:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "4207:27017"

  redis:
    image: redis
    restart: on-failure
    # ports:
    #   - "6379:6379"

  rest-api:
    build: apps/rest-api
    restart: always
    ports:
      - "127.0.0.1:4200:3420"